#!/usr/bin/env bash

function resetAccountRecovery() {

  createSMSUser \
    $TEST_USER_ACCOUNT_RECOVERY_EMAIL_1 \
    $TEST_USER_PASSWORD \
    $TEST_USER_PHONE_NUMBER \
    $TEST_USER_LATEST_TERMS_AND_CONDITIONS_VERSION

  createAuthAppUser \
    $TEST_USER_ACCOUNT_RECOVERY_EMAIL_2 \
    $TEST_USER_PASSWORD \
    $ACCOUNT_RECOVERY_USER_AUTH_APP_SECRET \
    $TEST_USER_LATEST_TERMS_AND_CONDITIONS_VERSION

  resetPassword $TEST_USER_ACCOUNT_RECOVERY_EMAIL_1 $TEST_USER_PASSWORD
  resetPassword $TEST_USER_ACCOUNT_RECOVERY_EMAIL_2 $TEST_USER_PASSWORD

  removeMfaMethods $TEST_USER_ACCOUNT_RECOVERY_EMAIL_1

  updateMfaSMS $TEST_USER_ACCOUNT_RECOVERY_EMAIL_1 $TEST_USER_PHONE_NUMBER "1"
  updateMfaAuthApp $TEST_USER_ACCOUNT_RECOVERY_EMAIL_2 $ACCOUNT_RECOVERY_USER_AUTH_APP_SECRET
}