name: Build and Push to API DEV account

env:
  AWS_REGION: eu-west-2
  DEV_GHA_DEPLOYER_ROLE: arn:aws:iam::653994557586:role/dev-auth-deploy-pipeline-GitHubActionsRole-QrtGginNnjDD
  DEV_ACCEPTANCE_ECR_REPO: acceptance-test-dev-testrunnerimagerepository-yh8assqv55do
  SELENIUM_BASE_CHROMIUM: selenium/standalone-chromium:132.0

on:
  workflow_dispatch:

concurrency:
  group: "build-and-push-tests-dev"
  cancel-in-progress: false

jobs:
  build-push-chromium:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ env.DEV_GHA_DEPLOYER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push (non-sp)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          target: auth-api
          build-args: |
            SELENIUM_BASE=${{ env.SELENIUM_BASE_CHROMIUM }}
          tags: |
            "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_ACCEPTANCE_ECR_REPO }}:latest"
            "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_ACCEPTANCE_ECR_REPO }}:latest-chromium"

      - name: Build and push (sp)
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          target: auth-ui
          build-args: |
            SELENIUM_BASE=${{ env.SELENIUM_BASE_CHROMIUM }}
          tags: |
            "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_ACCEPTANCE_ECR_REPO }}:sp-latest"
            "${{ steps.login-ecr.outputs.registry }}/${{ env.DEV_ACCEPTANCE_ECR_REPO }}:sp-latest-chromium"
